name: x86-windows

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release

jobs:

  build_x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: |
        ninja -C build

    - name: Copy files (Release)
      shell: bash
      run: |
        mkdir upload
        cp build/*.exe upload
        cp build/*.dll upload

    - name: Upload files (Release)
      uses: actions/upload-artifact@v4
      with:
        name: rtl_sdr_x64
        path: ${{github.workspace}}/upload

  build_x86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: |
        ninja -C build

    - name: Copy files (Release)
      shell: bash
      run: |
        mkdir upload
        cp build/*.exe upload
        cp build/*.dll upload

    - name: Upload files (Release)
      uses: actions/upload-artifact@v4
      with:
        name: rtl_sdr_x86
        path: ${{github.workspace}}/upload